version: "3.6"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: "elastic-search"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false

    ports:
      - "9200:9200"
      - "9300:9300"
  ##########################################################################################################################
  db:
    image: postgres
    container_name: "postgres_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=J93!s27Xma

  db-didl3:
    image: postgres
    container_name: "postgresdb_didl3"
    volumes:
      - didl3_data:/var/lib/postgresql/data
    ports:
      - "1000:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=identity
      - POSTGRES_PASSWORD=identity_password

  db-cred-schema:
    image: postgres
    container_name: "postgresdb_cred_schema"
    volumes:
      - cred_schema_data:/var/lib/postgresql/data
    ports:
      - "1001:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=cred_schema
      - POSTGRES_PASSWORD=cred_schema_password

  db-cred-ms:
    image: postgres
    container_name: "postgresdb_cred_ms"
    volumes:
      - cred_ms_data:/var/lib/postgresql/data
    ports:
      - "1005:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=cred_ms
      - POSTGRES_PASSWORD=cred_ms_password
  ##########################################################################################################################
  registry:
    image: dockerhub/sunbird-rc-core
    container_name: "registry"
    volumes:
      - ${PWD}/schemas:/home/sunbirdrc/config/public/_schemas
    environment:
      - connectionInfo_uri=jdbc:postgresql://postgres_db:5432/registry
      - connectionInfo_username=postgres
      - connectionInfo_password=J93!s27Xma
      - elastic_search_connection_url=es:9200
      - elastic_search_auth_enabled=false
      - elastic_search_username=elastic
      - elastic_search_password=
      - search_providerName=dev.sunbirdrc.registry.service.ElasticSearchService
      - sunbird_sso_realm=sunbird-rc
      - sunbird_sso_url=http://keycloak:8080/auth
      - sunbird_sso_admin_client_id=admin-api
      - sunbird_sso_client_id=registry-frontend
      - sunbird_sso_admin_client_secret=${KEYCLOAK_SECRET}
      - claims_url=http://claim-ms:8082
      - sign_url=http://certificate-signer:8079/sign
      - sign_health_check_url=http://certificate-signer:8079/health
      - signature_enabled=true
      - pdf_url=http://certificate-api:8078/api/v1/certificatePDF
      - certificate_health_check_url=http://certificate-api:8078/health
      - template_base_url=http://registry:8081/api/v1/templates/ #Looks for certificate templates for pdf copy of the signed certificate
      - sunbird_keycloak_user_set_password=true
      - filestorage_connection_url=http://file-storage:9000
      - filestorage_access_key=admin
      - filestorage_secret_key=12345678
      - filestorage_bucket_key=issuance
      - registry_base_apis_enable=false
      - sunbird_keycloak_user_password=abcd@123
      - logging.level.root=INFO
      - enable_external_templates=true
      - async_enabled=false
      - authentication_enabled=true
      - kafka_bootstrap_address=kafka:9092
      - webhook_enabled=false
      - webhook_url=http://localhost:5001/api/v1/callback
      - redis_host=redis
      - redis_port=6379
      - manager_type=DefinitionsManager
    ports:
      - "8081:8081"
    depends_on:
      - es
      - db
  ##########################################################################################################################
  keycloak:
    image: dockerhub/sunbird-rc-keycloak:nonce
    volumes:
      - ${PWD}/imports:/opt/jboss/keycloak/imports
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_PORT=5432
      - DB_DATABASE=registry
      - DB_USER=postgres
      - DB_PASSWORD=J93!s27Xma
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_LOGO=https://raw.githubusercontent.com/Sunbird-RC/demo-education-registry/federated_edu_registry/imports/ndearLogo.svg
      - KEYCLOAK_PORTAL_TITLE=Education
      - KEYCLOAK_PORTAL_SUB_TITLE=
      - VALIDATE_NONCE=false
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9990/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - db
  ##########################################################################################################################
  telemetry_service_clickhouse:
    image: clickhouse/clickhouse-server
    container_name: telemetry-clickhouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: "*!73uK*9xLEsnhIR"
    ports:
      - "8123:8123"
      - "9000:9000"
  telemetry-service:
    image: dubea/telemetry-service1:latest
    ports:
      - 9001:9001
    environment:
      telemetry_local_storage_type: "clickhouse"
      CLICKHOUSE_HOST: "http://telemetry-clickhouse:8123"
      CLICKHOUSE_USER: "clickhouse"
      CLICKHOUSE_PASSWORD: "*!73uK*9xLEsnhIR"
    depends_on:
      - telemetry_service_clickhouse
  ##########################################################################################################################
  bff_service:
    image: dubea/bff:2
    container_name: "bff-service"
    ports:
      - 3003:3000
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      update_config:
        parallelism: 1
        delay: 0s
        failure_action: rollback
        order: start-first
      # rollback_config:
      #  parallelism: 1
      # delay: 0s
      restart_policy:
        condition: on-failure

    environment:
      - name=value #Need to add the environment varibales in that
      - PORT=3000
      - CRED_URL=http://localhost:3002
      - DID_URL=http://localhost:3000
      - SCHEMA_URL=http://localhost:3001
      - MIDDLEWARE_URL=http://localhost:3003
      - REALM_ID=sunbird-rc
      - KEYCLOAK_CLIENT_ID=admin-api
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_SECRET}
      - KEYCLOAK_URL=http://localhost:8080/auth/
      - REGISTRY_URL=http://localhost:8081/
      - TESTVAR=ulp reference environment by tekdi
      - PROOF_OF_ASSESSMENT=clf0qfvna0000tj154706406y
      - PROOF_OF_ENROLLMENT=clf0rjgov0002tj15ml0fdest
      - PROOF_OF_BENIFIT=clf0wvyjs0008tj154rc071i1
      - TELEMETRY_URL=https://ulp.uniteframework.io/telemetry
  #############################################################################################################################
  bulk_issuance:
    image: dubea/bulk-issuance:1
    container_name: "bulk-issuance"
    ports:
      - 3007:3007
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      update_config:
        parallelism: 1
        delay: 0s
        failure_action: rollback
        order: start-first
      # rollback_config:
      #  parallelism: 1
      # delay: 0s
      restart_policy:
        condition: on-failure

    environment:
      - name=value #Need to add the environment varibales in that
      - PORT=3007
      - CRED_URL=http://localhost:3002
      - DID_URL=http://localhost:3000
      - SCHEMA_URL=http://localhost:3001
      - MIDDLEWARE_URL=http://localhost:3003
      - KEYCLOAK_URL=http://localhost:8080/auth/
      - REGISTRY_URL=http://localhost:8081/
      #      //schemaId
      - PROOF_OF_ASSESSMENT=clf0qfvna0000tj154706406y
      - PROOF_OF_ENROLLMENT=clf0rjgov0002tj15ml0fdest
      - PROOF_OF_BENIFIT=clf0wvyjs0008tj154rc071i1
      #keycloak
      - REALM_ID=sunbird-rc
      - KEYCLOAK_CLIENT_ID=admin-api
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_SECRET}

  ##########################################################################################################################
  credential_ms_service:
    image: dubea/credential-ms:sbrc
    container_name: "credential_ms"
    ports:
      - 3002:3333
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      update_config:
        parallelism: 1
        delay: 0s
        failure_action: rollback
        order: start-first
      #  rollback_config:
      #   parallelism: 1
      #  delay: 0s
      restart_policy:
        condition: on-failure

    environment:
      - DATABASE_URL=postgresql://cred_ms:cred_ms_password@postgresdb_cred_ms:1005/postgres?schema=public
      - IDENTITY_BASE_URL=http://did_l3_service:3332
  ##########################################################################################################################
  cred_schema_ms_service:
    image: dubea/cred-schema-ms:sbrc
    hostname: "cred_schema_ms_service"
    ports:
      - 3001:3000
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      update_config:
        parallelism: 1
        delay: 0s
        failure_action: rollback
        order: start-first
      # rollback_config:
      #  parallelism: 1
      # delay: 0s
      restart_policy:
        condition: on-failure

    environment:
      - DATABASE_URL=postgresql://cred_schemas:cred_schemas_password@postgresdb_cred_schema:1001/postgres?schema=public
      - IDENTITY_BASE_URL=http://did_l3_service:3332
  ##########################################################################################################################
  did_l3_service:
    image: dubea/did-l3:sbrc
    hostname: "did_l3_service"
    ports:
      - 3000:3332
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      update_config:
        parallelism: 1
        delay: 0s
        failure_action: rollback
        order: start-first
      # rollback_config:
      #  parallelism: 1
      # delay: 0s
      restart_policy:
        condition: on-failure
    environment:
      - DATABASE_URL=postgressql://identity:identity_password@postgresdb_didl3:1000/postgres?schema=public

volumes:
  postgres_data:
    driver: local
  didl3_data:
    driver: local
  cred_schema_data:
    driver: local
  cred_ms_data:
    driver: local
  clickhouse_data:
    driver: local
  keycloak_data:
    driver: local

networks:
  application_default:
    driver: bridge
